### ISSUE TITLE
Move configurations to lua

### ISSUE THREAD

**Issue by TheResplandor** [CyberMango/init.vimango#14]
Move all core configurations to Lua, including:
* LSP configurations using builtin lua api.
* Move vimscript/python/javascript plugins to lua alternatives when it makes sense.
* keymaps, settings, helper functions.

**Comment by TheResplandor** [comment]
Still WIP. action items left:

1. Many TODOs in the configs that should be resolved.
2. need to go over kickstarter's config and some other configs for new ideas/information.
      configs list: https://github.com/nullchilly/nvim , https://github.com/B4mbus/nvim , https://github.com/NavePnow/dotfiles/tree/main/.config/nvim , https://github.com/0xRZ/.dotfiles/tree/master/nvim/.config/nvim
3. Packer should be automatically installed on a new machine.
4. all aucmds should be in groups, and should be deleted on a reload of the configs. Every file should have its own group to avoid deleting aucmds of other files when only this file is reloaded.

old config capabilities that wont be ported for now:
-snippets.
-extended status line.
-autocompletion.
-fuzzy finding.

**Comment by TheResplandor** [comment]
Done in PR #19

**Comment by CyberMango** [comment]
v
